FROM node:alpine

RUN apk update \
	&& apk upgrade \
	&& apk add --no-cache --upgrade bash \
	&& apk add npm dumb-init

WORKDIR /app

COPY ./package.json .
RUN npm install

COPY . .
RUN npm run build

ENTRYPOINT ["/usr/bin/dumb-init", "--"]