FROM node:alpine

RUN apk update \
	&& apk upgrade \
	&& apk add --no-cache --upgrade bash \
	&& apk add npm dumb-init

WORKDIR /app

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["sh", "-c", "npm install && npm run build && npm run start"]