# Generated by Django 5.0.3 on 2024-03-28 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralGameLogs',
            fields=[
                ('game_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1', models.ForeignKey(db_column='player1', on_delete=django.db.models.deletion.CASCADE, related_name='general_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(db_column='player2', on_delete=django.db.models.deletion.CASCADE, related_name='general_player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GeneralGameLogs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGameLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=20)),
                ('round', models.IntegerField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_final', models.BooleanField()),
                ('player1', models.ForeignKey(db_column='player1', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(db_column='player2', on_delete=django.db.models.deletion.CASCADE, related_name='tournament_player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TournamentGameLogs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentgamelogs',
            constraint=models.UniqueConstraint(fields=('tournament_name', 'round'), name='tournament_game_id'),
        ),
    ]
